    # run

    - name: Update apt cache
      apt: update_cache=yes
      become: yes
      tags:
      - core
      - provision

    - name: Install common dependencies
      apt: pkg={{ item }}
      become: yes
      with_items:
      - libpython2.7-stdlib
      - python-httplib2
      - apt-transport-https
      - python
      - python-pip
      - python-dev
      - python-openssl
      - build-essential
      - libssl-dev
      - libffi-dev
      tags:
      - core
      - provision

    - name: Upgrade pip
      pip: name=pip extra_args=--upgrade
      become: yes
      tags:
      - core
      - provision

    - name: Install python modules to support SNI SSL requests
      pip: name={{ item }}
      become: yes
      with_items:
      - urllib3
      - pyopenssl
      - ndg-httpsclient
      - pyasn1
      tags:
      - core
      - provision

    - name: Install tmux terminal multiplexer
      apt: pkg=tmux
      become: yes

    - name: Install curl
      apt: pkg=curl
      become: yes
      tags:
      - core
      - provision

    - name: Install Timezone data
      apt: pkg=tzdata
      become: yes
      tags:
      - core
      - run

    - name: Set timezone
      copy: content=Australia/Melbourne dest=/etc/timezone
      become: yes
      tags:
      - core
      - run

    - name: Set Local Time
      shell: dpkg-reconfigure --frontend noninteractive tzdata
      become: yes
      tags:
      - core
      - run

    - name: Install NTP
      apt: pkg={{ item }}
      with_items:
        - ntp
        - ntpdate
      become: yes
      tags:
      - core
      - run

    - name: Install PCP
      apt: pkg=pcp
      become: yes
      tags:
      - core
      - run

    - name: Change PCP directory ownership
      file: path=/var/log/pcp/pmmgr state=directory owner=pcp group=pcp
      become: yes
      tags:
      - core
      - run

    # development

    - name: Install avahi
      apt: pkg=avahi-daemon
      become: yes
      tags:
      - core
      - development

    - name: Install git
      apt: pkg=git-core
      tags:
      - core
      - development
      become: yes

    - name: Install vim
      apt: pkg=vim
      become: yes
      tags:
      - core
      - development

    - name: Setup paths for vim
      file: path={{ item }} state=directory
      with_items:
      - ~/.vim/autoload
      - ~/.vim/bundle
      tags:
      - core
      - development

    - name: Install pathogen
      get_url: url=https://raw.github.com/tpope/vim-pathogen/master/autoload/pathogen.vim dest=~/.vim/autoload/pathogen.vim
      tags:
      - core
      - development

    - name: Install vim plugin
      git: repo={{ item.repo }} dest=~/.vim/bundle/{{ item.name }}
      with_items:
      - {repo: "https://github.com/scrooloose/nerdtree.git", name: nerdtree}
      - {repo: "https://github.com/ctrlpvim/ctrlp.vim.git", name: ctrlp}
      - {repo: "https://github.com/ntpeters/vim-better-whitespace.git", name: vim-better-whitespace}
      - {repo: "https://github.com/airblade/vim-gitgutter.git", name: vim-gitgutter}
      tags:
      - core
      - development

    - name: Update .vimrc
      lineinfile: dest=~/.vimrc line="{{ item }}" create=yes
      with_items:
      - execute pathogen#infect()
      - syntax on
      - filetype plugin indent on
      - :set tabstop=2
      - :set shiftwidth=2
      - :set expandtab
      - :set nobackup
      - :set noswapfile
      - let g:ctrlp_map = '<c-p>'
      - let g:ctrlp_cmd = 'CtrlP'
      - autocmd BufEnter * EnableStripWhitespaceOnSave
      tags:
      - core
      - development
