    # run

    - name: Update apt cache
      apt: update_cache=yes
      become: yes
      tags:
      - core
      - provision

    - name: uri ansible module requirements
      apt: pkg={{ item }}
      become: yes
      with_items:
      - libpython2.7-stdlib
      - python-httplib2
      tags:
      - core
      - provision

    - name: Install curl
      apt: pkg=curl
      become: yes
      tags:
      - core
      - provision

    - name: Install Timezone data
      apt: pkg=tzdata
      become: yes
      tags:
      - core
      - run

    - name: Set timezone
      copy: content=Australia/Melbourne dest=/etc/timezone
      become: yes
      tags:
      - core
      - run

    - name: Set Local Time
      shell: dpkg-reconfigure --frontend noninteractive tzdata
      become: yes
      tags:
      - core
      - run

    - name: Install NTP
      apt: pkg={{ item }}
      with_items:
        - ntp
        - ntpdate
      become: yes
      tags:
      - core
      - run

    - name: Install PCP
      apt: pkg=pcp
      become: yes
      notify:
      - Change PCP directory ownership
      tags:
      - core
      - run

    # development

    - name: Install avahi
      apt: pkg=avahi-daemon
      become: yes
      tags:
      - core
      - development

    - name: Install git
      apt: pkg=git-core
      tags:
      - core
      - development
      become: yes

    - name: Install vim
      apt: pkg=vim
      become: yes
      tags:
      - core
      - development

    - name: Setup paths for vim
      file: path={{ item }} state=directory
      with_items:
      - ~/.vim/autoload
      - ~/.vim/bundle
      tags:
      - core
      - development

    - name: Install pathogen
      get_url: url=https://raw.github.com/tpope/vim-pathogen/master/autoload/pathogen.vim dest=~/.vim/autoload/pathogen.vim
      tags:
      - core
      - development

    - name: Update .vimrc
      lineinfile: dest=~/.vimrc line="{{ item }}" create=yes
      with_items:
      - execute pathogen#infect()
      - syntax on
      - filetype plugin indent on
      - :set tabstop=2
      - :set shiftwidth=2
      - :set expandtab
      - :set nobackup
      - :set noswapfile
      tags:
      - core
      - development

    - name: Install NERD tree
      git: repo=https://github.com/scrooloose/nerdtree.git dest=~/.vim/bundle/nerdtree
      tags:
      - core
      - development

    - name: Install ctrlp.vim
      git: repo=https://github.com/ctrlpvim/ctrlp.vim.git dest=~/.vim/bundle/ctrlp
      tags:
      - core
      - development
